meta_product_name: "Clubster"
meta_title: "Clubster - Never miss a single party"
meta_description: "Sign up and discover the best events in berlin, based on your music and club preferences. Results are smply sent to your whatsapp whenever you want!"
meta_image: "lobster-pink.png" # should exist in `app/assets/images/`
